version: "3.7"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork
    environment:
      - API_BASE_URL=http://backend:8088/erp-api  

  eairp:
    build:
      context: ./core
      dockerfile: CoreDockerfile
    ports:
      - "8088:8088"
    image: wansenai/eairp:latest  
    networks:
      - mynetwork

networks:
  mynetwork: