spring:
  datasource:
    url: jdbc:mysql://124.221.106.96:3306/wansenerp_v2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: WanSenTechMysql
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
  data:
    redis:
      database: 9
      host: 124.221.106.96
      port: 6379
      # 密码
      password: '000415'
      # 连接超时时间
      timeout: 2000s
      lettuce:
        pool:
          max-active: 32   #最大连接数据库连接数,设 0 为没有限制
          max-idle: 16     #最大等待连接中的数量,设 0 为没有限制
          max-wait: 300ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          min-idle: 16     #最小等待连接中的数量,设 0 为没有限制

flowable:
  async-executor-activate: false
  database-schema-update: true