spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wansenerp_v2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: PaSsw0Rd
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 20
          max-wait: 100
          max-idle: 20
          min-idle: 5
      timeout: 10000
flowable:
  async-executor-activate: true
  database-schema-update: true